/*********************************
 * 
 * Version       Date         Name           Description
 * ======================================================================
 * V1.0         14-01-2022    Develoepr1     Add menthod implemented
 * 
 * 
 ***********************************/



/********
 * Name: Calculator
 * Author:Debasis
 * Date:13-01-2022
 * 
 ************/


public with sharing class Calculator {
    public Calculator() {

    }
    Public integer add(integer a, integer b){
        return a+b;
    }

}
